export const webSafeFonts = new Set([
  'Arial',
  'Brush Script MT',
  'Courier New',
  'Garamond',
  'Georgia',
  'Helvetica',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
]);

export const cssSystemFonts = new Set([
  '-moz-button',
  '-moz-desktop',
  '-moz-dialog',
  '-moz-document',
  '-moz-field',
  '-moz-info',
  '-moz-list',
  '-moz-pull-down-menu',
  '-moz-window',
  'caption',
  'cursive',
  'emoji',
  'fangsong',
  'fantasy',
  'icon',
  'math',
  'message-box',
  'menu',
  'monospace',
  'sans-serif',
  'serif',
  'small-caption',
  'status-bar',
  'system-ui',
  'ui-monospace',
  'ui-rounded',
  'ui-sans-serif',
  'ui-serif',
]);
